repos:
  - repo: local
    hooks:
      - id: make-tidy
        name: Run make tidy
        entry: make tidy
        language: system
        types: [go]
        stages: [pre-push]
      - id: make-audit
        name: Run make audit
        entry: make audit
        language: system
        types: [go]
        stages: [pre-push]

